### ISSUE TITLE
Logs only get sent when stopping the application

### ISSUE THREAD

**Issue by sroze** [logzio/logzio-log4j2-appender#20]
Thank you for this appender. It happened though that the logs are getting sent by it only when the application is being stopped. My log4j configuration is the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration monitorInterval="60">
    <Appenders>
        <Console name="Console-Appender" target="SYSTEM_OUT">
            <PatternLayout>
                <pattern>
                    [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
                </pattern>>
            </PatternLayout>
        </Console>

        <LogzioAppender name="Logzio">
            <logzioToken>[token]</logzioToken>
            <logzioType>java</logzioType>
            <logzioUrl>https://listener.logz.io:8071</logzioUrl>
            <addHostname>true</addHostname>
            <drainTimeoutSec>1</drainTimeoutSec>
            <debug>true</debug>
        </LogzioAppender>
    </Appenders>

    <Loggers>
        <Root level="info">
            <AppenderRef ref="Logzio"/>
            <AppenderRef ref="Console-Appender"/>
        </Root>
    </Loggers>
</Configuration>
```

I'd expect it to "drain and flush" every second but it doesn't. Literally sents all the logs only when I stop the application (CTRL+C). Any hint on why it could behave this way? 

Note that the console appender works fine (i.e. it's displaying the logs on my console straight away.

**Comment by sroze** [comment]
Note that I tried with just the `logzio*` parameters, without any success. Also worth a note, there is nothing in the logs (even if I turn the `level="debug"`) that would suggest a malfunction.

**Comment by asafm** [comment]
@sroze - Please last comment, if still relevant?

**Comment by sroze** [comment]
I've used another logger at the end as I couldn't make this one work. Which means I can't provide more details to you, unfortunately.

**Comment by asafm** [comment]
Sorry for that @sroze
